         </div>
         <div id="footer">
            <div class="bottomborder">
					<img alt="" src="http://www.lib.umd.edu/dcr/collections/mdhc/images/edge_bl_red.gif" class="leftcorner">
					<div class="identification">
						This is a project of the 
						<a href="http://www.lib.umd.edu/dcr/">Office of Digital Collections and Research</a>
						&gt;
						<a href="http://www.lib.umd.edu/">University Libraries</a>
						&gt;
						<a href="http://www.umd.edu/">University of Maryland</a>
					</div>
					<img alt="" src="http://www.lib.umd.edu/dcr/collections/mdhc/images/edge_br_red.gif" class="rightcorner">
            </div>
				<div class="copyright">
					&copy; 2008 University of Maryland Libraries
				</div>
         </div>
      </div>
      <script type="text/javascript">
         var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
         document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
      </script>
      <script type="text/javascript">
         var pageTracker = _gat._getTracker("UA-4965595-1");
         pageTracker._initData();
         pageTracker._trackPageview();
      </script>
